packages:
  - { name: wget }
  - { name: anyenv }
  - { name: yarn }
  - { name: openssl }
  - { name: mas }
  - { name: awscli }
  - { name: fzf }
  - { name: docker }
  - { name: ffmpeg }
  - { name: jq }
  - { name: tree }
  - { name: pwgen }
  - { name: emacs }
  - { name: heroku }
